
services:

  frontend:
    build: ./FE
    container_name: frontend
    restart: always
    networks:
      - backend
      

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
#      - ./nginx/web.conf:/etc/nginx/conf.d/web.conf
      - ./nginx:/etc/nginx/conf.d
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - processing
      - frontend
    networks:
      - backend

     
  processing:
    container_name: processing
    build: ./processing
    env_file:
      - ./processing/.env
    environment:
      - PYTHONPATH=/app
    command: gunicorn -w 1 -b 0.0.0.0:8000 processing:app
    volumes:
      - ./processing/:/app
    depends_on:
      - processing-db
    networks:
      - backend

      
  processing-db:
    container_name: processing-db
    image: postgres:15
    restart: always
    env_file:
      - ./processing/.env
    ports:
      - "5436:5432"
    volumes:
      - processing_data:/var/lib/postgresql/data
    networks:
      - backend      
      

volumes:
  processing_data:


networks:
  backend: